from datetime import datetime

# Lista completa de fornecedores
fornecedores_lista = [
    ("Utimix", "https://www.utimix.com/", "(11)95300-7505", True),
    ("Zein", "https://www.zein.com.br/", "(11)94725-1366 - João", True),
    ("Top Rio", "https://www.instagram.com/toprio_importadora_ofc/", "(21) 97038-5924 - Giulia", True),
    ("Nipocenter", "https://www.atacadaonipocenter.com.br/", "(11) 5584-3318", True),
    ("Imporiente", "https://www.instagram.com/imporiente.oficial/", "(11) 98198-8482", True),
    ("Keita", "https://www.instagram.com/keitaimportadora/", "(11) 93663-0302", True),
    ("Garden Produtos de Madeira", "https://www.gardenprodutosdemadeira.com/", "(26) 996-5311", False),
    ("Art Mixing", "https://linkpol.com.br/", "(71) 98397-0546", False),
    ("Alibaba", "https://portuguese.alibaba.com/", "(86) 571-8502-2088", False),
    ("AB Importações", "https://abimportacoes.com.br/", "(86) 00138-26433", False),
    ("Asia Rooms", "http://www.asiarooms.com.br/", "", False),
    ("Ame.art", "https://www.instagram.com/ame.art.br/", "(16) 99308-0073", False),
    ("Aluminum Fortaleza", "https://aluminumfortaleza.com.br/", "", False),
    ("Amargate", "https://www.instagram.com/amargateoficial/", "(16) 99308-0073", False),
    ("Americanas", "https://www.americanas.com.br/", "(11) 4004-3131 / (11) 99865-3621", False),
    ("ArtBrilhe", "https://www.instagram.com/Loja/artbrilhe/", "(81) 99943-9600", False),
    ("ArtPizza", "https://www.artpizza.com.br/", "(11) 2291-2272", False),
    ("Atacadão", "https://www.atacadao.com.br/", "", False),
    ("Avulse", "http://www.avpec.com.br/", "(86) 0326-5909", False),
    ("Azi Jóias", "https://azimportadoraonline.com/", "(54) 99211-9408", False),
    ("Bellani Importadora", "https://www.instagram.com/bellaniimportadora/", "", False),
    ("Brasaitec", "https://brasaitec.com.br/", "(11) 3834-4709", False),
    ("Bronze", "https://www.bronze.ind.br/", "(53) 4005-7023", False),
    ("Bussola para Rosa", "https://www.instagram.com/bussolapararosa/", "(11) 99146-5960", False),
    ("ENVOXX", "https://www.envoxx.br/", "(46)99206-4575", False),
    ("Brasil Distribuidora", "https://www.brasildistribuidora.com.br/", "(11) 98947-0096", False),
    ("Cabralisa", "https://www.cabralisa.com.br/", "(21) 2471-4170", False),
    ("Casalandia GB", "https://casalandia.com/", "(47) 99973-4165", False),
    ("Class Home", "https://www.classhome.br/", "(19) 3926-3113", False),
    ("Casas Bahia", "https://www.casasbahia.com.br/", "(11) 4002-8788", False),
    ("DM Toys", "https://dmtoys.com.br/", "(82) 2127-2078", False),
    ("Eleva (Koron)", "https://www.instagram.com/elevacs.magazine/", "(11) 98217-8887", False),
    ("Fabricante Blanquearte", "https://www.fabricanteblanquearte.com.br/", "(11) 97253-9845", False),
    ("Ferco (Kolors)", "https://ferrocolors.com.br/", "(51) 98405-0183", False),
    ("Fixa Loucas", "https://www.instagram.com/fixaloucas/", "(11) 96073-2754", False),
    ("Frato", "https://lojasfrato.vteximg.com.br/", "", False),
    ("FWB", "https://www.fwb.com.br/", "(16) 99308-0073", False),
    ("Geral Plasforma", "https://www.geralplasforma.com.br/", "(11) 2771-1837", False),
    ("GKS", "http://www.gks.ind.br/", "(11) 4178-6100", False),
    ("GLOempari", "https://www.gloempari.com.br/", "(11) 2267-5518 / (11) 97125-0000", False),
    ("GOLDshop", "https://www.instagram.com/goldshopimportacoes/", "(86) 99208-0073", False),
    ("Grife Line", "https://grifeline.com/", "", False),
    ("Home Design", "http://gadeashop.wixsite.com/", "", False),
    ("Home Goods Importadora", "https://viallags.lojavirtualnuvem.com.br/", "(11) 2206-3036", False),
    ("House Time", "https://www.instagram.com/housetimebrasil/", "", False),
    ("Irmãos Cremonte", "https://www.instagram.com/irmaoscremonte/", "", False),
    ("Isolefe", "http://boykobichinhos.com.br/", "(11) 3533-6904", False),
    ("Import+", "https://importmais.com/", "(11) 99622-2020", False),
    ("Lojaskell", "https://www.lojaskell.com.br/", "(080) 318 8211", False),
    ("Maria Utilidades", "https://www.mariautilidades.com.br/", "(15) 3533-2274", False),
    ("MariaCortinovis", "https://www.instagram.com/mariacortinovis/", "", False),
    ("Megatoy", "https://www.instagram.com/megatoy/", "(19) 3271-2179", False),
    ("Mix Atacado", "https://www.instagram.com/mixatacado/", "", False),
    ("MR Injetados", "http://www.mrinjetados.com.br/", "(19) 3242-5171", False),
    ("Monte Líbano", "https://www.montelibano.com.br/", "(11) 3942-3775", False),
    ("M2R", "https://www.b2wmarketplace.com.br/", "(21) 2105-7991", False),
    ("Multlaser", "https://www.multilaser.com.br/", "(11) 2161-5656", False),
    ("Nautika", "https://www.nautika.com.br/", "(11) 2485-6832", False),
    ("Nelson", "https://www.nelson.ind.br/", "(47) 3535-5646", False),
    ("Niazi Importados", "https://www.instagram.com/niazi.importados/", "(11) 96862-2838", False),
    ("Nilson", "https://www.nilson.com.br/", "(11) 2413-2235", False),
    ("Noar", "https://noarvip.com.br/", "", False),
    ("Pais & Filhos", "https://www.instagram.com/paisfilhos/", "(16) 99308-0073", False),
    ("P & R Brinquedos", "https://www.perbrinquedos.com.br/", "(19) 99486-1337", False),
    ("Plasgel", "https://www.instagram.com/plasgelofc/", "(54) 3209-6444", False),
    ("Plast Bella Importadora", "https://www.instagram.com/plastbellaimportadora/", "(11) 97302-1627", False),
    ("Rox Home", "https://www.instagram.com/roxhome/", "", False),
    ("Rox Master", "https://roxmaster.com.br/", "(19) 3484-6159", False),
    ("Rochedo", "https://www.rochedo.ind.br/", "(54) 3225-4900", False),
    ("Sony", "https://www.sony.com.br/", "(11) 2065-6777", False),
    ("Roda", "https://gpollock.com.br/", "", False),
    ("Salvia", "https://www.salvia.ind.br/", "(47) 3026-0404", False),
    ("Salvia Cachita Import", "https://www.instagram.com/salviacachitaimport/", "", False),
    ("SORVAIO", "https://www.sorvaio.com/", "(16)99306-3073", False),
    ("StarLux", "https://www.instagram.com/starluxbr/", "", False),
    ("TOP CASA", "https://www.instagram.com/topcasabr/", "", False),
    ("TopClass", "https://www.topclass.com.br/", "(11) 4825-3931", False),
    ("TT Brasil", "https://ttbrasil.com.br/", "(11) 98845-2637", False),
    ("Uatt", "https://uatt.com.br/", "", False),
    ("Unik Home", "https://www.instagram.com/unikhomeimportador/", "", False),
    ("Unimix", "https://unimix.com.br/", "(86) 3251-6659", False),
    ("Vércia", "https://www.vercia.ind.br/", "(11) 2092-9688", False),
    ("VMV", "https://www.vmv.com.br/", "(11) 2935-6788", False),
    ("Wellmix", "https://www.wellmix.com.br/", "(11) 2512-2705", False),
    ("WillA", "https://www.willa.com.br/", "(21) 2221-1187", False),
    ("Wire Store", "https://www.instagram.com/wirestore.br/", "(16) 99308-0073", False),
    ("zerotoys", "https://zerotoys.com.br/", "", False),
    ("Baraze", "https://www.baraze.com.br/", "(11) 2915-6000", False),
    ("Casa Do Caos", "https://www.instagram.com/casadocaosoficial/", "(11) 3812-3400", False),
    ("CHR", "https://www.instagram.com/chrbrasil/", "", False),
    ("Caneca", "https://www.caneca.com.br/", "(47) 3286-7045", False),
    ("Caneca Home", "https://www.instagram.com/canecahome/", "(11) 3862-7045", False),
    ("Euro Home", "https://www.instagram.com/eurohomeoficial/", "", False),
    ("Pasta Criare", "https://pastacriare.com.br/", "", False),
    ("Pratas Douradas Atacadista", "https://www.instagram.com/pratasdouradasatacadista/", "", False),
    ("Linapse", "https://linapse.com.br/", "(46) 3647-2165", False),
    ("LA Plasticos", "https://laplasticos.com/", "", False),
    ("Casa e Vida", "https://www.instagram.com/casaevida.br/", "(11) 99935-7345", False),
    ("C. Vida Importadora", "https://www.instagram.com/cvidaimportadora/", "", False),
    ("Metalocasa", "https://metalocasa.com.br/", "(16) 99308-0073", False),
    ("Global Gifts", "https://www.globalgifts.com.br/", "(11) 4762-7200", False),
    ("Malssi Platinium", "https://www.malssiplatinium.com.br/", "(16) 3512-2006", False),
    ("Quality House", "https://www.instagram.com/qualityhouse.br/", "", False),
    ("Zatti Mix", "https://www.instagram.com/zattimix/", "(11) 95635-3007", False),
    ("Ecocor Comercial", "https://www.ecocor.eco.br/", "(11) 3225-6457", False),
]

# Gerar JSON
fornecedores_json = []
for idx, (nome, site, telefone, prioritario) in enumerate(fornecedores_lista, 1):
    fornecedores_json.append({
        "id": idx,
        "nome": nome,
        "site_instagram": site,
        "telefone": telefone,
        "observacoes": "",
        "prioritario": prioritario,
        "ativo": True,
        "created_at": datetime.now().isoformat()
    })

# Salvar em arquivo
import json
with open('fornecedores_completo.json', 'w', encoding='utf-8') as f:
    json.dump({
        "fornecedores": fornecedores_json,
        "proximo_id": len(fornecedores_json) + 1
    }, f, indent=2, ensure_ascii=False)

print(f"Gerado arquivo com {len(fornecedores_json)} fornecedores!")
print(f"   - {sum(1 for f in fornecedores_json if f['prioritario'])} prioritarios")
print(f"   - {sum(1 for f in fornecedores_json if not f['prioritario'])} normais")
